POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5sdWtpY2hldmEiLCJpZCI6IjYxNTg1ZTczY2EyNDZlM2ZhMTUxZDRkOCIsImlhdCI6MTYzMzI1NDE0NX0.i28aMr382zC3lDmVO9zHczNdv3x3Tvo4YuBdHiUeeFY

{
    "title": "Suomen historia",
    "author": "Natalia",
    "url": "www.google.fi",
    "likes": 1
}